# Generated by Django 3.0.2 on 2020-01-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_customer_product_salesorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=61),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=61),
        ),
    ]
