# Generated by Django 3.0.2 on 2020-01-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0005_auto_20200128_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.CharField(blank=True, max_length=250, null=True)),
                ('request_url', models.CharField(blank=True, max_length=250, null=True)),
                ('resp_code', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
